services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    # network_mode: host
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus:/etc/prometheus/"
    # network_mode: host
